// <auto-generated />
using AccountBalanceViewer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountBalanceViewer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240619071711_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountBalanceViewer.Entities.AccountBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CEOCarExpenses")
                        .HasColumnType("float");

                    b.Property<double>("Canteen")
                        .HasColumnType("float");

                    b.Property<double>("Marketing")
                        .HasColumnType("float");

                    b.Property<double>("ParkingFines")
                        .HasColumnType("float");

                    b.Property<double>("RnD")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AccountBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
